title.archive: Archives

archive.count: "%d posts"

node.lists: Nodes
tag.lists: Tags

menu.index: Index
menu.node: Nodes
menu.more: More

button.home: Back to home
button.prev_post: Previous post
button.next_post: Next post
button.top: Back to top

comments.title: Comments
comments.powered: "Powered by <a href=\"https://disqus.com/\">Disqus</a>"
comments.noscript: Please enable JavaScript to view the comments.

widget.recent_posts: Recent Posts

widget.nodes: Nodes
widget.nodes.explore: Explore all nodes

widget.status: Blog Status
widget.status.posts: Posts
widget.status.nodes: Nodes
widget.status.tags: Tags

widget.toc: Table of contents

footer.about: About
